### ISSUE TITLE
setup.py: Allow comments in requirements.txt files

### ISSUE THREAD

**Issue by jayvdb** [moremoban/pypi-mobans#37]
When there is a comment in `requirements.txt`, it is loaded into `setup.py`, and the result (under setuptools 21) is 

```python
running install_scripts
Traceback (most recent call last):
  File "setup.py", line 211, in <module>
    cmdclass=SETUP_COMMANDS,
  File "/opt/python/3.5.5/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/3.5.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.5.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 257, in run
    self.distinfo_dir)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 427, in egg2dist
    distribution=self.distribution)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wheel/metadata.py", line 177, in pkginfo_to_dict
    new_requirements = sorted(convert_requirements(requirements))
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wheel/metadata.py", line 234, in convert_requirements
    parsed_requirement = pkg_resources.Requirement.parse(req)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2833, in parse
    req, = parse_requirements(s)
ValueError: not enough values to unpack (expected 1, got 0)
```

**Comment by jayvdb** [comment]
This can be fixed by stripping those lines while loading the files.

**Comment by chfw** [comment]
As of today, current version setuptools is 39.2.0. Don't you think setuptools version 21 is too old?

**Comment by jayvdb** [comment]
Travis Python 3.4.4 provides pip 8.1.2 and setuptools 18.0.1 .  We have found those to be too old to be useful.

Travis Python 9.0.1 provides 9.0.1 and setuptools-38.2.4 .  We find that this environment defaults changes and breaks too frequently.

So we pin to pip 9.0 and setuptools 21.  It keeps us sane.
As a result, I havent looked at whether a newer setuptools might work correctly.

If the setup.py doesnt support older versions, we should also implement a setuptools version check in the template. Then the templates can check if the included requirements files use features like `# ..` and set the minimum setuptools version dynamically.

**Comment by ayan-b** [comment]
Please assign this issue to me. @jayvdb @chfw

**Comment by jayvdb** [comment]
No worries ... assigned :P

(this isnt coala so there isnt any infrastructure to add you to the org, assign you, etc.  but nobody else is working on this .. go for it)
