### ISSUE TITLE
gitignore template fails switching from pkg to repo

### ISSUE THREAD

**Issue by jayvdb** [moremoban/pypi-mobans#94]
failure on https://github.com/moremoban/moban/commit/c8449308f5b5698db71b2b86f10febb8faa499a0

https://travis-ci.org/moremoban/moban/jobs/556113013

```console
moban -m mobanfile
Cloning https://github.com/jayvdb/pypi-mobans...
Templating setup.py to setup.py
Templating __init__.py.jj2 to moban/__init__.py
Templating _version.py.jj2 to moban/_version.py
Templating custom_conf.py.jj2 to docs/conf.py
Templating travis.yml to .travis.yml
Templating requirements.txt.jj2 to requirements.txt
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/moban", line 10, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/main.py", line 34, in main
    count = handle_moban_file(moban_file, options)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/main.py", line 149, in handle_moban_file
    mobanfile.handle_moban_file_v1(moban_file_configurations, options)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/mobanfile/__init__.py", line 81, in handle_moban_file_v1
    number_of_templated_files = handle_targets(merged_options, targets)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/mobanfile/__init__.py", line 141, in handle_targets
    engine.render_to_files(jobs_for_each_engine[template_type])
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/plugins/template.py", line 134, in render_to_files
    self._render_with_finding_data_first(sta.data_file_index)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/plugins/template.py", line 163, in _render_with_finding_data_first
    template_abs_path, template, data, output
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/plugins/template.py", line 111, in apply_template
    template, data, output_file
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/jinja2/engine.py", line 133, in apply_template
    rendered_content = template.render(**data)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/build/moremoban/moban/.moban.d/moban_gitignore.jj2", line 1, in top-level template code
    {% extends "gitignore.jj2" %}
  File "/home/travis/.cache/moban/repos/pypi-mobans/templates/gitignore.jj2", line 25, in top-level template code
    {% include 'gitignore/' + gitignore_language + '.gitignore' %}
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: gitignore/Python.gitignore
Makefile:10: recipe for target 'update' failed
make: *** [update] Error 1
```

**Comment by jayvdb** [comment]
The problem was I didnt use `submodule: true`

This could be automatically handled inside moban, but I am cautious about adding more git stuff to moban, as I really want he git layer to be handed by pyfs with https://github.com/moremoban/moban/issues/205
